/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedStepperRouteImport } from './routes/_protected/stepper'
import { Route as ProtectedSettingsRouteImport } from './routes/_protected/settings'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedCoversRouteImport } from './routes/_protected/covers'
import { Route as ProtectedBroadcastRouteImport } from './routes/_protected/broadcast'
import { Route as ProtectedBroadcastIndexRouteImport } from './routes/_protected/broadcast/index'
import { Route as ProtectedTeachersTeacherListRouteImport } from './routes/_protected/teachers/teacher-list'
import { Route as ProtectedClubsClubListRouteImport } from './routes/_protected/clubs/club-list'
import { Route as ProtectedClubsClubIdRouteImport } from './routes/_protected/clubs/$clubId'
import { Route as ProtectedBroadcastNewRouteImport } from './routes/_protected/broadcast/new'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedStepperRoute = ProtectedStepperRouteImport.update({
  id: '/stepper',
  path: '/stepper',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedCoversRoute = ProtectedCoversRouteImport.update({
  id: '/covers',
  path: '/covers',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBroadcastRoute = ProtectedBroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBroadcastIndexRoute = ProtectedBroadcastIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedBroadcastRoute,
} as any)
const ProtectedTeachersTeacherListRoute =
  ProtectedTeachersTeacherListRouteImport.update({
    id: '/teachers/teacher-list',
    path: '/teachers/teacher-list',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedClubsClubListRoute = ProtectedClubsClubListRouteImport.update({
  id: '/clubs/club-list',
  path: '/clubs/club-list',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedClubsClubIdRoute = ProtectedClubsClubIdRouteImport.update({
  id: '/clubs/$clubId',
  path: '/clubs/$clubId',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedBroadcastNewRoute = ProtectedBroadcastNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProtectedBroadcastRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/broadcast': typeof ProtectedBroadcastRouteWithChildren
  '/covers': typeof ProtectedCoversRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRoute
  '/stepper': typeof ProtectedStepperRoute
  '/broadcast/new': typeof ProtectedBroadcastNewRoute
  '/clubs/$clubId': typeof ProtectedClubsClubIdRoute
  '/clubs/club-list': typeof ProtectedClubsClubListRoute
  '/teachers/teacher-list': typeof ProtectedTeachersTeacherListRoute
  '/broadcast/': typeof ProtectedBroadcastIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/covers': typeof ProtectedCoversRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/settings': typeof ProtectedSettingsRoute
  '/stepper': typeof ProtectedStepperRoute
  '/broadcast/new': typeof ProtectedBroadcastNewRoute
  '/clubs/$clubId': typeof ProtectedClubsClubIdRoute
  '/clubs/club-list': typeof ProtectedClubsClubListRoute
  '/teachers/teacher-list': typeof ProtectedTeachersTeacherListRoute
  '/broadcast': typeof ProtectedBroadcastIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_protected/broadcast': typeof ProtectedBroadcastRouteWithChildren
  '/_protected/covers': typeof ProtectedCoversRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/_protected/stepper': typeof ProtectedStepperRoute
  '/_protected/broadcast/new': typeof ProtectedBroadcastNewRoute
  '/_protected/clubs/$clubId': typeof ProtectedClubsClubIdRoute
  '/_protected/clubs/club-list': typeof ProtectedClubsClubListRoute
  '/_protected/teachers/teacher-list': typeof ProtectedTeachersTeacherListRoute
  '/_protected/broadcast/': typeof ProtectedBroadcastIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/broadcast'
    | '/covers'
    | '/dashboard'
    | '/settings'
    | '/stepper'
    | '/broadcast/new'
    | '/clubs/$clubId'
    | '/clubs/club-list'
    | '/teachers/teacher-list'
    | '/broadcast/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/covers'
    | '/dashboard'
    | '/settings'
    | '/stepper'
    | '/broadcast/new'
    | '/clubs/$clubId'
    | '/clubs/club-list'
    | '/teachers/teacher-list'
    | '/broadcast'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_protected/broadcast'
    | '/_protected/covers'
    | '/_protected/dashboard'
    | '/_protected/settings'
    | '/_protected/stepper'
    | '/_protected/broadcast/new'
    | '/_protected/clubs/$clubId'
    | '/_protected/clubs/club-list'
    | '/_protected/teachers/teacher-list'
    | '/_protected/broadcast/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/stepper': {
      id: '/_protected/stepper'
      path: '/stepper'
      fullPath: '/stepper'
      preLoaderRoute: typeof ProtectedStepperRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/covers': {
      id: '/_protected/covers'
      path: '/covers'
      fullPath: '/covers'
      preLoaderRoute: typeof ProtectedCoversRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/broadcast': {
      id: '/_protected/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof ProtectedBroadcastRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/broadcast/': {
      id: '/_protected/broadcast/'
      path: '/'
      fullPath: '/broadcast/'
      preLoaderRoute: typeof ProtectedBroadcastIndexRouteImport
      parentRoute: typeof ProtectedBroadcastRoute
    }
    '/_protected/teachers/teacher-list': {
      id: '/_protected/teachers/teacher-list'
      path: '/teachers/teacher-list'
      fullPath: '/teachers/teacher-list'
      preLoaderRoute: typeof ProtectedTeachersTeacherListRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/clubs/club-list': {
      id: '/_protected/clubs/club-list'
      path: '/clubs/club-list'
      fullPath: '/clubs/club-list'
      preLoaderRoute: typeof ProtectedClubsClubListRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/clubs/$clubId': {
      id: '/_protected/clubs/$clubId'
      path: '/clubs/$clubId'
      fullPath: '/clubs/$clubId'
      preLoaderRoute: typeof ProtectedClubsClubIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/broadcast/new': {
      id: '/_protected/broadcast/new'
      path: '/new'
      fullPath: '/broadcast/new'
      preLoaderRoute: typeof ProtectedBroadcastNewRouteImport
      parentRoute: typeof ProtectedBroadcastRoute
    }
  }
}

interface ProtectedBroadcastRouteChildren {
  ProtectedBroadcastNewRoute: typeof ProtectedBroadcastNewRoute
  ProtectedBroadcastIndexRoute: typeof ProtectedBroadcastIndexRoute
}

const ProtectedBroadcastRouteChildren: ProtectedBroadcastRouteChildren = {
  ProtectedBroadcastNewRoute: ProtectedBroadcastNewRoute,
  ProtectedBroadcastIndexRoute: ProtectedBroadcastIndexRoute,
}

const ProtectedBroadcastRouteWithChildren =
  ProtectedBroadcastRoute._addFileChildren(ProtectedBroadcastRouteChildren)

interface ProtectedRouteChildren {
  ProtectedBroadcastRoute: typeof ProtectedBroadcastRouteWithChildren
  ProtectedCoversRoute: typeof ProtectedCoversRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  ProtectedStepperRoute: typeof ProtectedStepperRoute
  ProtectedClubsClubIdRoute: typeof ProtectedClubsClubIdRoute
  ProtectedClubsClubListRoute: typeof ProtectedClubsClubListRoute
  ProtectedTeachersTeacherListRoute: typeof ProtectedTeachersTeacherListRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedBroadcastRoute: ProtectedBroadcastRouteWithChildren,
  ProtectedCoversRoute: ProtectedCoversRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedStepperRoute: ProtectedStepperRoute,
  ProtectedClubsClubIdRoute: ProtectedClubsClubIdRoute,
  ProtectedClubsClubListRoute: ProtectedClubsClubListRoute,
  ProtectedTeachersTeacherListRoute: ProtectedTeachersTeacherListRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
